### ISSUE TITLE
hello.com: Cannot start or run due to incompatibility with 64-bit versions of Windows.

### ISSUE THREAD

**Issue by BoQsc** [ibara/a80#1]
**Operating System:** Windows 10 Home

**Prerequisites:** 
* [hello.asm](https://github.com/ibara/a80/blob/main/hello.asm)

**Course of action:**

```
dub
a80.exe hello.asm
hello.com
```

![image](https://user-images.githubusercontent.com/21064622/175895525-8d547e07-c729-46fe-b0f0-8545c355512d.png)

![image](https://user-images.githubusercontent.com/21064622/175896466-1f47a51c-f22f-4866-900d-80da72b7129e.png)

**Comment by BoQsc** [comment]
https://board.flatassembler.net/topic.php?p=185888

**Comment by ibara** [comment]
This is as expected. This assembler generates code for the **Intel 8080** (https://en.wikipedia.org/wiki/Intel_8080) which is an entirely different processor family than the x86 CPU you have in your machine.
